### ISSUE TITLE
Gateway activates when using the system key to move windows

### ISSUE THREAD

**Issue by flurick** [vicr123/theshell#1]

**Comment by vicr123** [comment]
Ok, maybe I'll add a toggle to the settings asking if the super key should open the gateway. Thanks for your suggestion :)

**Comment by flurick** [comment]
I don't mind opening it with super, but it matters if I just tap that one key or if I am trying to do something else like move a window.

**Comment by vicr123** [comment]
Ok. I'll look into making the super key (and other hotkeys) activate when the key is released, rather than when it is pressed. Thanks :)

**Comment by vicr123** [comment]
Unfortunately I couldn't make theShell let go of the hotkey unless the Gateway doesn't open. I've put a toggle in the settings (which you can access by clicking on one of the labels on the top of the bar) to make theShell not capture the super key on startup. :)

The change was pushed to the blueprint branch and should come out in the next release of theShell.
