### ISSUE TITLE
qmake and make command

### ISSUE THREAD

**Issue by Mom-Assistance** [vicr123/theshell#13]
Where can I get qmake, and the make command gives back "make: *** No targets specified and no makefile found.  Stop." qmake gives "qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory" in Ubuntu.  Just help me with what exactly I need to do to get it running
![image](https://cloud.githubusercontent.com/assets/24907538/26128273/ddd12bc6-3a59-11e7-9c1a-a75e323e7ba8.png)

**Comment by Technohacker** [comment]
You might be looking for CMake, not qmake

sudo apt install cmake

**Comment by vicr123** [comment]
@Mom-Assistance You probably don't have Qt 5 installed. I'm not quite sure what the packages you'll need on Ubuntu are, but as long as they provide the Qt 5 libraries and build system, they should be ok. :)

**Comment by Mom-Assistance** [comment]
I think I found the place to get the libraries https://download.qt.io/archive/qt/5.8/5.8.0/

**Comment by Technohacker** [comment]
@Mom-Assistance you might want to use the package manager instead

**Comment by Mom-Assistance** [comment]
Ok, I'll keep looking at what i can do to get it working.  @vicr123  can I have a link to theShell discord server my old account got hacked

**Comment by vicr123** [comment]
@Mom-Assistance https://discord.gg/g2XgKRH is the link you're looking for. :)

**Comment by vicr123** [comment]
I'm going to go ahead and close this issue.
