### ISSUE TITLE
Volume hotkey bug

### ISSUE THREAD

**Issue by ThePixelPolygon** [vicr123/theshell#14]
If your keyboard has volume hotkeys, you can raise the volume past 100%

Screenshot:
![screenshot17-34-55-2017-05-18](https://cloud.githubusercontent.com/assets/28792503/26224454/6cbef5e2-3bf0-11e7-883f-6a5e120b4404.png)

**Comment by vicr123** [comment]
@ThePixelPolygon This is intended behaviour.
