### ISSUE TITLE
theShell breaks after closing Kodi

### ISSUE THREAD

**Issue by MrDiamond123** [vicr123/theshell#16]
I was running Kodi but when i got out of it theShell "breaks"

theBar is missing, theSettings don't appear

It starts working when you restart though.

**Comment by MrDiamond123** [comment]
@vicr123 Any info about this bug?

**Comment by vicr123** [comment]
I'll have to get Kodi working on my computer if I want to examine this. I'll take a look soon. :)

**Comment by MrDiamond123** [comment]
I am going to test if it happens "now" in a VM both stable and blueprint

**Comment by MrDiamond123** [comment]
No info on issue - Closing Issue
