### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Maaajaaa** [vicr123/theshell#2]
I tried to built it on Ubuntu 16.10 but figured out that **some dependencies are missing in your README**:
- libsystemd
- libakonadi
- libcups
I also couldn't figure out which ubuntu package of akonadi is the right one.
Mattis

**Comment by vicr123** [comment]
Ahh, thanks. I'll update that as soon as I can. What versions of Akonadi are there? :)

**Comment by Maaajaaa** [comment]
There are:

- libakonadi-dev (doesn't work, have tried it)
- libkf5akonadi-dev
- libkf5akonadi-dev-bin
- libkf5akonadicalendar-dev
- llibkf5akonadicalendar-dev
- libkf5akonadimime-dev
- libkf5akonadinotes-dev
...
[more](http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=akonadi+dev&searchon=names)

**Comment by vicr123** [comment]
I think libkf5akonadi-dev should work. I'll also put on the README that if there are KDE 4 and KDE 5 libraries in the repositories, they should get the KDE 5 versions. :)

**Comment by Maaajaaa** [comment]
just rerun make with  libkf5akonadi-dev but it doesn't work yet.

**Comment by vicr123** [comment]
What error are you getting?

**Comment by Maaajaaa** [comment]
`thewaveworker.h:30:29: fatal error: akonadi/control.h: No such file or directory`

**Comment by vicr123** [comment]
Does `/usr/include/KF5/AkonadiCore/control.h` exist on your system?

Oh, and thanks for telling me about these depencencies. I'm horrible at tracking them. :)

**Comment by Maaajaaa** [comment]
Yes it is there.

**Comment by vicr123** [comment]
OK, I worked it out. Turns out I was using KDE4 PIM libraries rather than KF5. 

Could you try opening `thewaveworker.h` and up the top, near the bottom of the `#include`s, replace

`#include <akonadi/control.h>`
`#include <akonadi/servermanager.h>`
`#include <akonadi/session.h>`

with
`#include <KF5/AkonadiCore/control.h>`
`#include <KF5/AkonadiCore/servermanager.h>`
`#include <KF5/AkonadiCore/session.h>`

If this works for you, I'll do a commit to fix that up when my Git starts working again. :)

**Comment by Maaajaaa** [comment]
Fixed it by changing the include to `include <KF5/AkonadiCore/control.h>` but there should be a better solution like a soft-link or an option for make.

**Comment by vicr123** [comment]
Cool. I'll commit that change as soon as I am able to. Thanks. :)

**Comment by Maaajaaa** [comment]
I figured out some more required libs/packages:
- libxcb-utils-dev
- libxcursor-dev
but now I'm hanging at some different kind of error:
`mainwindow.cpp:607:51: error: no matching function for call to ‘QAction::QAction()’
                     QAction* action = new QAction();`
btw: can't aur tell you the required build-depencies?

**Comment by vicr123** [comment]
Thanks, I'll take a look. Sorry about all the build issues.

Can you try adding `#include <QAction>` at the top of mainwindow.h? You are using Qt 5, correct? :)

No, `namcap` doesn't work for me. :(

**Comment by SparkyCola** [comment]
I figured out some more required libs/packages:
- libxcb-utils-dev
- libxcursor-dev
but now I'm hanging at some different kind of error:
`mainwindow.cpp:607:51: error: no matching function for call to ‘QAction::QAction()’
                     QAction* action = new QAction();`
btw: can't aur tell you the required build-depencies?

**Comment by Maaajaaa** [comment]
The error suggested: `QAction(QObject *parent)` and some more. I tried `QAction* action = new QAction(this);` which made make work but it hung on start (I also have to install the dependencies made by you). And yes I use Qt 5.

**Comment by Maaajaaa** [comment]
Anyway I followed your suggestion and here's the full error message (same as before I did change the line):
mainwindow.cpp: In member function ‘void MainWindow::updateMpris()’:
mainwindow.cpp:607:51: error: no matching function for call to ‘QAction::QAction()’
                     QAction* action = new QAction();
                                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:40:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMenu:1,
                 from mainwindow.h:16,
                 from mainwindow.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:174:5: note: candidate: QAction::QAction(QActionPrivate&, QObject*)
     QAction(QActionPrivate &dd, QObject *parent);
     ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:174:5: note:   candidate expects 2 arguments, 0 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:89:5: note: candidate: QAction::QAction(const QIcon&, const QString&, QObject*)
     QAction(const QIcon &icon, const QString &text, QObject* parent);
     ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:89:5: note:   candidate expects 3 arguments, 0 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:88:5: note: candidate: QAction::QAction(const QString&, QObject*)
     QAction(const QString &text, QObject* parent);
     ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:88:5: note:   candidate expects 2 arguments, 0 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:87:14: note: candidate: QAction::QAction(QObject*)
     explicit QAction(QObject* parent);

**Comment by vicr123** [comment]
Can you try `QAction* action = new QAction(NULL);` please? parent should be an optional parameter, but for some reason your system doesn't like it.

**Comment by Maaajaaa** [comment]
I checked the Qt documentation which says it's not optional (might have changed during some versions, I have Qt5.6.1)

**Comment by vicr123** [comment]
Hmm... In my QAction header, I have `explicit QAction(QObject *parent = nullptr);` Either way, I think I might initialize my QAction objects from now on. (Qt 5.7, but definitely had no problems when I was usinig Qt 5.6) Thanks :)

Does it build now? :)

**Comment by Maaajaaa** [comment]
Build runs with both the `QAction(this)` and `QAction(NULL)`.

**Comment by vicr123** [comment]
Thanks. I'll push commits with the changes as soon as I can. :)
