### ISSUE TITLE
Increase the size of text in hidpi screen 

### ISSUE THREAD

**Issue by samtux** [vicr123/theshell#24]
First to congratulate you on this great project, it really was something I was looking for some time ago. I would like to ask how I do to increase the size of the text for hidpi screens?, since the texts are very small.

**Comment by vicr123** [comment]
Thanks :D

Does changing the DPI in System Settings > Adjust Screen Resolution > Scale Display do anything? I know I've built hidpi support into theShell, but if that doesn't work, just tell me. :)

What distribution are you using? :)

**Comment by samtux** [comment]
The distribution used is Arch Linux, specifically Manjaro Deepin and the installation of **theshell** is through the theshell-blueprint 6.2b-0 package in AUR repository [1]. I tried to use the option that tells me, but it does not work, the option _System Settings > Adjust Screen Resolution > Scale Display_ does not exist in the installed version. Here a screenshot.

[imgur screenshot](http://i.imgur.com/xdtWXbq.gifv)

I appreciate if it is possible support in the future to increase the scaling of text and icons.

Again, great desktop for Linux!!!

[1] https://aur.archlinux.org/packages/theshell-blueprint/

**Comment by vicr123** [comment]
Ahh, do you have the `kde-cli-tools` package installed? That provides the configuration window for KScreen which theShell uses for screen management :)

**Comment by samtux** [comment]
Thanks @vicr123. It does not save scaling changes, but it allows me to change the resolution. This is not saving the changes, so every time I log in I have to change the screen resolution.

**Comment by vicr123** [comment]
Ahh ok. I'll see about moving away from KScreen in theShell 7.1. :)

**Comment by vicr123** [comment]
Options have been added to the latest Blueprint and ts-startsession. :)
