### ISSUE TITLE
Crashing when logging in

### ISSUE THREAD

**Issue by ThePixelPolygon** [vicr123/theshell#26]
Hi there! I seem to have encountered a bug where theShell crashes when logging in while a laptop is plugged into the wall. When the laptop is running off the battery, it works just fine.

**Comment by vicr123** [comment]
Ahh! I know there is currently a major bug where sometimes theShell won't start up properly, and this may be it! I'll do some testing to determine if this is the issue or not. Thanks for the bug report! :D

If this is the same issue then you've solved a problem that's been giving me headaches for a while :D

**Comment by Riley-the-dog** [comment]
I think I'm having the same problem, but I'm running it in a virtual box, so I don't know if it can tell the difference between when it's plugged in or on battery.

**Comment by vicr123** [comment]
@Riley-the-dog Ahh the problem seems to be resolved in the blueprint version of theShell, and that should make its way to stable soon. :)

And yes, if you're in VirtualBox it can tell if you're running on battery or not :)

**Comment by vicr123** [comment]
This issue should be resolved now, go ahead and comment if you're still having this issue :)
