### ISSUE TITLE
Screenshot functionality should check if a screenshot window is already open before opening a new one.

### ISSUE THREAD

**Issue by Nevvulo** [vicr123/theshell#28]
When pressing `PRT SC` (print screen) on the keyboard, it'll open a new `screenshotWindow`. However, if you press `PRT SC` again whilst you have the screenshot window open, it'll open another new `screenshotWindow`. I think there should be precautions/checks put in place to check if a `screenshotWindow` already exists before creating a new one to prevent issues and things like this from happening: 
![image](https://user-images.githubusercontent.com/26913683/29493204-6eb53256-85d5-11e7-8087-e3836617e818.png)
 *Obviously this is exaggerated, but it isn't uncommon to accidentally open two screenshot windows at the same time.*

One solution to this could be to disable the keyboard whilst you have the screenshot window opened, as opening theGateway is also possible whilst the screenshot window is opened. Disabling the keyboard could fix this issue too, but it's up to you.

Thanks for your time, and thanks for creating such a great project!

**Comment by MrDiamond123** [comment]
Well some people use tab and arrow keys to select options of things

Like me sometimes :P So don't disable the keyboard

**Comment by FriendsNone** [comment]
Maybe disable the PrtSc button?

**Comment by Nevvulo** [comment]
Closing this due to old age. @vicr123 has explained that this may be difficult to implement, moreover new screenshot features are being added, so code is probably being refactored.  Let me know if I should re-open this 👍
