### ISSUE TITLE
ldconfig: /usr/lib/libthe-libs.so.1 is not a symbolic link

### ISSUE THREAD

**Issue by Technohacker** [vicr123/theshell#3]
This message pops up after the installation of the `theLibs` AUR package. Might not be an error but just wanted to let you know :)

**Comment by vicr123** [comment]
Is this after building or after installing? :)

**Comment by Technohacker** [comment]
from what i remember, it was after it installs the libraries, during `ldconfig` :)

**Comment by vicr123** [comment]
Was this when the-libs was installing or when theShell was installing? :)

**Comment by Technohacker** [comment]
@vicr123 when the-libs is installing :)

**Comment by MrDiamond123** [comment]
I know a fix. When I was installing/building theShell the first thing it was building was tsscreenlock, change it so it builds the-libs builds first.

(How I fixed it myself was by getting the-libs 1st then installing theShell)

**Comment by vicr123** [comment]
@Technohacker Should be fixed in the latest `the-libs` version now. :)

**Comment by Technohacker** [comment]
Works like a charm :D
