### ISSUE TITLE
T̡͐̌͊ͬͣͨ͐̐̀h́̿̽̈́̋̋͠i̧̢̎̒ͤ͡s̷̄͢͠ ͒ͮͫ͂͐͝i̸ͮͣ̊̾ͦͥ̆ͧͩsͧ̈̒̌̚ ̢ͩͪͪ͐ͩ̉̐ͭaͭ͑ͪ́͏ ̈̂̚ź͗̓̽̇͐̓͆͢a̸̎͑̋̈́̓ͥͪlͫ̒͊̇ͧ͂̐̕g̋̓̄̋͊̍̇ͤ͠õ̒̾҉̷ ͪ̓̊̀҉t͒͏e͛͋s̡ͦͣt́҉̵̸!̒͗̓̏͟

### ISSUE THREAD

**Issue by Nevvulo** [vicr123/theshell#33]
T̷̅ͭ͌̎͑͗̇̄͒ͩͯͧ̌́̂̑ͧ͗̌̊ͬ͏̸̧̡̀̀͘͢h́̑̍ͣ̃̀̊ͨ̈́ͨ̇̋͋̓̎̅̌̏̏ͦ̄ͪ̍͊ͪ̽̾͋ͣ͐̈́́ͩ̄̄ͧͯ̓͒͊̏̐̏̀̉̆̾̉̔ͣ͑̽̀͗̓̎͛̈́͛̚̚̚̚҉̴̧̨̡́͘͟͢͟҉̵̨̧̀͘͞͡͡͞͏҉̴i̷̸̸̇ͦ͋̍ͯ̔̂̀ͪ̃̔ͩ͋ͬ̐̔̓ͮͮͥ̈ͯͥͧ̏̃̿̅ͧ͂͒̃̌̈̿ͭ̆ͧ̇̽̃̍̓̒̊ͭ̃̇́ͪ̽͒͆ͨ̇̑͊ͨ̉͗͂ͬ̂͂͗ͤ̿ͭ͘͜͠͞s̵̵̢̛̛͛͂͒̇ͯ͂̒̊̈͛̋ͩ̔͋̋͗̽ͫ̒͂̅̓̐̄̄̐̋̒̊̎̐̂̽̎̑̇̄ͮ̀̈́̾ͤͪͤ̔̅̇͂̆́ͤ͋ͧ͗̈̋̀̂̊̏́ͩ̋̄̓̋̂̽̒͂͂̔̒͊̓̒̏ͪͭ͂̎̉̂ͫ̌̃ͣͦ́̀́̚͘͢͞ ̵̸̴̷̸̡̡̧̡̄͛̏̑̈͒̏̊̿ͦͤ̓̀̄͛͗̊̍̇ͪ̌̃̎̀́͘̕͟͜͢͠͞͝͞͡i̸̸̵̷̧̧̛̓͂͋̃ͭ͂ͦ̉̏̐̊̇͑̊̐̌̏ͮ̏̅ͭͣ͗ͪ͋̍̒̈̂̋͊̎ͣͥͩ̀͋̅͌̉ͨͬ̌ͨ͐̐̍ͮ̓̒͒ͫ̎́ͥ͊̀̉͐ͥ̾ͩ̍̓ͮ̆̍́͌ͫ̽̔͑̑͑̚̕̕̕͟͢͟͟͝ś̷̡ͩͪ̃ͩ͋͗́ͤ̏̃̕͟͢͜͡͏̧̛ ̒͗͛̽̍̒̓̇͑̆ͭ̐̃ͩ̑ͧ̿̍͛̈́̆͐̔̆̓͛̏͑ͪ̒̀̽̐ͫ̆͑͂̌͐͂̿̑ͭ̉̂̐͆͛̂ͭ͆̎ͫ͂ͮ́̐ͩ̊̈́ͫ͗̽̌ͤ̒̎̓ͦ̍͂̓́̚͏̢҉̷̴̵̢̨̡̢̛͘̕͟͞a̴ͣ͐̎̓̈́̑̂̉́̐̎̽҉̸̨͟͝͏̡҉͡ ̶̷̅ͧͮͥ̈ͥ̊̏ͧͭ̐ͤͭ͛̓̄̏̈͋͆ͯ͂ͦ̆ͭ̑̇̅̎ͦͮ̈́̽͆ͬͣ͂͌͗͗̎̿̽ͮ̅́̒ͥͩ̾̂ͦ͋ͤͤ̉̾̂̀ͫ̓̎̚͡҉̸̵̵͢͠҉̴̛́҉̶́͟͢͢͞z̵̵̈͆͛̔͆͒ͣͤ͒͌͌̉͗̂ͬ͋ͩ̏̒̋̑ͦ̾ͨ͐̊̿͋ͨ̉̂̈̍̑ͭ̐ͪ͒͛ͬ͊͋ͯ̆͌́̑͆ͤͧͦͧ̈́͌́̉͋ͯ͋ͬ̂ͧ̽̐ͯ̈͒̚a̴ͬͯ̾ͧ͛ͧͬͣͨͫ͛͊̉̔͑̓ͮ͌̄̉͘͠l̴̸̨̡̛̄̌̌̍͐̀͢҉̀҉̶̸̵̨̨̀͢͟͝͠҉̷͞g͑ͮ͒̒̔̂ͣ͊͗̑͛̐ͬ̔ͭ̓̀ͦ̎ͨ̔͐̊ͨ͆̎ͪ̾̋͗͒͗͌̅̾̆͊ͮ̍͌̆̔̆͗͋̑̓̈̌̇̿̒͑̒̊ͤ̐̉͊̌̿̎͋̓̆͊͌ͨ̐̎ͥ̋͛ͯ̔̒̐̔͆̒̓ͥ͐o̴̸̡̢̔ͨ̇̏͗ͬ̇ͪ̔ͭ̇͘͡͝͡͡͠ ̵̷̨̢̔͑̓͋ͭ͂̔ͯ̃̂͛ͪ͋ͣͦͥ́̎̓͂̉̉̿ͭ̄̓͂̂ͥͫ̆̏̔͒͂ͫͪ̌ͧ̉͑ͪͬ͂͂̆̏͂̏ͦ̑̑̏͗ͣͬ͂̈̀́̕͜͠͠͡͡͞t̴̒ͮ̈̀͛ͤͫ̿̇̄̿̔ͥ̑̌̈̎ͭ̒ͬͨ̐ͦ̑͊ͦ͌̀ͯ̔͗ͤ̉̎ͬ̓̋̓̈́̑̑̑̐̈́ͥͥ̌̾ͪ̾͐͋ͤͬ̃ͣͦ̄̈́ͭ̐̎̇ͬ̊ͧͫ̕͜͟͏̷̢̛͠ȩ̵̶̊̓̌̍ͧ̍̃̌̍͜͢͜͡҉̷̵̴̀͢͜s̸̨̊̂̐ͩͫͪ̽̉̂̍̿͐̄ͣ̃̒͗ͧ͗ͥ̓̅̿̈́̎̀̈́͠͡҉҉̵̴̴̷̛͢͟͢t̓͂͂̃ͭ͆͂͋ͮͪͣ̽͌͌̉ͧ̓ͤ̆̏͗̆ͧ̈̿͌̒͂̇̒̈́̓ͨͦ̍̔͊̂̓̿̊ͬ͂̒̎̓͆̍̈̋̚҉̡̡͘͟͟͝͏!̷̵̵̴̶̨̛̃̿ͧ̏ͬͨ͆ͬ͊͛͑̋̓ͩͥ̽͋̒ͮ̔̈̑̃̐ͬ͊̎́ͤ́́́̀́́́̚̕͘͜͟͟͜͝

**This bug report was at request of @vicr123 to test zalgo in GitHub.**

**Comment by vicr123** [comment]
Ok, so Zalgo works in GitHub too. Thanks Blake

**Comment by Nevvulo** [comment]
No problem mate. It definitely looks interesting.

**Comment by Technohacker** [comment]
Oh god XD
