### ISSUE TITLE
Configure- System Setting Module - Desktop Effect doesn't respect theme style.

### ISSUE THREAD

**Issue by llde** [vicr123/theshell#41]
[
![screenshot13-43-58-2018-07-10](https://user-images.githubusercontent.com/11397728/42507985-8727fd22-8436-11e8-9077-04d0e3ef4843.png)
](url)

As the screenshot show, there is the zone of the options of Desktop effect part that is white despite behing the dark theme.

**Comment by vicr123** [comment]
That seems to be an issue with KDE System Settings. Can you see if setting a dark theme in KDE System Settings fixes the issue?

EDIT: For theShell System Settings, you can click on the clock and then in the top right corner there'll be a button that says "System Settings" :)

**Comment by llde** [comment]
KDE system setting is basically unusable in theShell.

![screenshot14-00-52-2018-07-10](https://user-images.githubusercontent.com/11397728/42508642-bfef8538-8438-11e8-8f0e-fc719cb3b687.png)

**Comment by vicr123** [comment]
I feel that KDE System Settings might be hardcoded to use KDE's colour settings so at this point I don't think I have control over this issue, but if you log into KDE and change to a dark theme, and come back into theShell, does the text still appear black?

**Comment by llde** [comment]
I'm updating the system. I wil try when it end.

**Comment by llde** [comment]
Setted the theme as Dark Breeze, and text style as Contemporary and the issues seem resolved.

**Comment by vicr123** [comment]
Ahh okay, that's a problem for the KDE developers then :)

If you do run into any problems with Qt apps and Contemporary (for example I know Desktop Effects has some issues showing checkboxes and buttons) you can try running it in Breeze by using the command `[app name] --style=breeze` or in your Desktop Effects case `kcmshell5 kwineffects --style=breeze` :)
