### ISSUE TITLE
translation not there 

### ISSUE THREAD

**Issue by SolarAquarion** [vicr123/theshell#45]
Cannot create /home/solaraquarion/build/theshell-blueprint/src/theshell-blueprint-repo/statuscenter/NetworkPane/translations/fr_FR.ts: No such file or directory
make[2]: *** [Makefile:1233: genlang] Error 1
make[2]: Leaving directory '/home/solaraquarion/build/theshell-blueprint/src/theshell-blueprint-repo/statuscenter/NetworkPane'

**Comment by SolarAquarion** [comment]
fixed by  #9dfdbcad0cf123756fac44130a0a4fcf5f0ead21

**Comment by vicr123** [comment]
My bad, sorry about that
