### ISSUE TITLE
Many battery power notifications whenever the computer is on AC

### ISSUE THREAD

**Issue by leocura** [vicr123/theshell#50]
Whenever I plug the AC cable, theShell notifies me of its removal. I simply cannot use it while charging because the notifications keeps popping up.
Could it be hardware? Perhaps, but I don't notice anything like that while using KDE or XFCE.

edit: When I say I don't notice anything like it, I mean _anything_ like it. There are no broken cords or a bad power outlet on the way.
I'm running Debian buster, over Ubuntu repo. Apart from that, no major bug noticed.

![image](https://user-images.githubusercontent.com/36933459/68066225-614aaa80-fd13-11e9-897b-c2e2f704a4ce.png)

**Comment by vicr123** [comment]
Known issue, the power management in theShell really needs some work. Should be fixed in theShell 9.0 :)

Unfortunately the Ubuntu repo is a bit out of date; Ubuntu really hates shipping up to date packages and theShell needs a more recent version than what's currently packaged with Ubuntu 18.04. I'll probably look into packaging a version for Ubuntu 20.04 when it comes out though :)

**Comment by leocura** [comment]
> Known issue, the power management in theShell really needs some work. Should be fixed in theShell 9.0 :)
> 
> Unfortunately the Ubuntu repo is a bit out of date; Ubuntu really hates shipping up to date packages and theShell needs a more recent version than what's currently packaged with Ubuntu 18.04. I'll probably look into packaging a version for Ubuntu 20.04 when it comes out though :)

All good then, is there any way for me to drop that specific notification as a workaround?

**Comment by vicr123** [comment]
Unfortunately not on theShell 7.1 (which is what's on Ubuntu at the moment I'm pretty sure). It was added in theShell Blueprint I think :(

**Comment by vicr123** [comment]
I've made changes to theShell Blueprint that should resolve this issue. If the issue persists, please reopen the issue and tell me what device it's not working properly with. :)
