### ISSUE TITLE
Translation documentation

### ISSUE THREAD

**Issue by Hayao0819** [vicr123/theshell#56]
Hello, I'm Japanese.
I really like TheShell and I am thinking to translate TheShell into Japanese.
But I can't find TRANSLATORS.md in README.md. Could you tell me where it is?

**Comment by vicr123** [comment]
TRANSLATORS.md seems to have been mistakenly moved to the `shell` directory :sweat_smile: 

If you want to make translations, I've given you permission to make Japanese translations at https://translate.vicr123.com/ :)

**Comment by Hayao0819** [comment]
I already registered there, but couldn't find TheShell project, so I'm currently forking Git into [my repository](https://github.com/Hayao0819/theshell).
I would like to translate TheShell into Japanese with my friends and send a pull request.

**Comment by Hayao0819** [comment]
I'm sorry I checked and found TheShell.
I remove the fork and translate it there.

**Comment by vicr123** [comment]
I just had a look at the repository and it turns out I haven't yet generated the Japanese translation files. Give me about 20 minutes (hopefully) and I'll go ahead and get that sorted for you :)

**Comment by vicr123** [comment]
I've generated the Japanese translation files and they're ready over here: https://translate.vicr123.com/projects/theshell

Translate theShell Desktop first, and then you can translate whatever else you like :upside_down_face:

**Comment by Hayao0819** [comment]
Thank you very much
I'll do my best to translate theShell
It seems that my friends will help me together.
