### ISSUE TITLE
Translation page problem

### ISSUE THREAD

**Issue by yamader** [vicr123/theshell#57]
I am already logged in https://translate.vicr123.com . But I cannot see the contents unless logging out.
I've already cleared browser cache and I also tried using a few other browser , but the issue did not fixed.
![image](https://user-images.githubusercontent.com/45691925/75245831-e6515680-5811-11ea-985d-9119d924b3cc.png)

**Comment by vicr123** [comment]
You'll need to tell me your username so I can give you permissions to translate on the website :)

**Comment by yamader** [comment]
Thanks :) My ID is "yamad_linuxer".

**Comment by vicr123** [comment]
Done, should work now :)
