### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by that1polish** [vicr123/theshell#64]
i am having a memory issue with the shell what is the limit

**Comment by TheTechRobo** [comment]
I believe theShell has been discontinued, as its codebase wasn't too great.

Try out theDesk if you want a successor.

**Comment by TheTechRobo** [comment]
I believe theShell has been discontinued, as its codebase wasn't too great.

Try out theDesk if you want a successor.

**Comment by that1polish** [comment]
Thanks, I'll check it out.

**Comment by that1polish** [comment]
I will do that when I get arch going I'm having issues with that
