### ISSUE TITLE
Test Bug Title

### ISSUE THREAD

**Issue by vicr123** [vicr123/theshell#7]
This is a test bug created to test the new ts Bugreporting program.

**Comment by Technohacker** [comment]
Bugreporter works! 😀

**Comment by vicr123** [comment]
This is a test comment created to test the new ts Bugreporting program

@Technohacker Thanks! :D

**Comment by colorfulchair** [comment]
@vicr123 Ping! :P

**Comment by vicr123** [comment]
@aren-cllc Thanks! :D

**Comment by vicr123** [comment]
Testing Markdown...

*italic*
**bold**
`code`
**bold with *italic* text**
*italic with **bold** text*

`code with *markdown* **inside**`

**Comment by vicr123** [comment]
```cpp
int main() {
    // this is C++ code
    int a = 3 + 5;
    return a - 8;
}
```

**Comment by ByteOfMelon** [comment]
This is a test comment.

**Comment by vicr123** [comment]
@TheRandomMelon Your test comment seems to work :D

**Comment by ByteOfMelon** [comment]
@vicr123 🥇

**Comment by Vrabbers** [comment]
ew curly braces on same line

**Comment by Technohacker** [comment]
@Vrabbers I prefer that style of code :P

**Comment by OfficialRain** [comment]
I wanna make a test comment :P

**Comment by bountifulellie** [comment]
hello victor and turtle from the bug reporter
c:

**Comment by OfficialRain** [comment]
Is this thing even on (anymore)?

**Comment by Technohacker** [comment]
Yup :P
