### ISSUE TITLE
Ahead of Time

### ISSUE THREAD

**Issue by OfficialRain** [vicr123/theshell#9]
theWave always goes one thing over what time unit it's on.

Examples:
5 seconds = 6 seconds
5 minutes = 6 minutes
5 hours = 6 hours

**Comment by OfficialRain** [comment]
When setting a timer I forgot to mention

**Comment by vicr123** [comment]
Ok, I'll look into this.

**Comment by Technohacker** [comment]
Would seem like an OBOE

**Comment by OfficialRain** [comment]
Could be anything honestly.

**Comment by vicr123** [comment]
theWave has been discontinued at this point, so I'm going to close this :)
